import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const appleVarieties = [
  {
    name: 'Fuji',
    origin: 'Japan',
    bestUse: 'Eating Fresh',
    description: 'A sweet and crisp apple with a firm texture, perfect for snacking.',
    flavorProfile: 'Sweet',
    harvestSeason: 'Late Fall',
    popularUses: ['Snacking', 'Salads'],
  },
  {
    name: 'Granny Smith',
    origin: 'Australia',
    bestUse: 'Baking',
    description: 'A tart, green apple that holds its shape well when baked.',
    flavorProfile: 'Tart',
    harvestSeason: 'Late Fall',
    popularUses: ['Baking', 'Juicing'],
  },
  {
    name: 'Honeycrisp',
    origin: 'USA',
    bestUse: 'Eating Fresh',
    description: 'A juicy and crisp apple with a balanced sweet-tart flavor.',
    flavorProfile: 'Sweet-Tart',
    harvestSeason: 'Early Fall',
    popularUses: ['Snacking', 'Salads'],
  },
  {
    name: 'Gala',
    origin: 'New Zealand',
    bestUse: 'Eating Fresh',
    description: 'A mild and sweet apple with a thin skin, great for kids.',
    flavorProfile: 'Sweet',
    harvestSeason: 'Late Summer',
    popularUses: ['Snacking', 'Desserts'],
  },
  {
    name: 'Red Delicious',
    origin: 'USA',
    bestUse: 'Eating Fresh',
    description: 'A classic red apple with a mildly sweet flavor and soft texture.',
    flavorProfile: 'Sweet',
    harvestSeason: 'Fall',
    popularUses: ['Snacking', 'Decorations'],
  },
  {
    name: 'Golden Delicious',
    origin: 'USA',
    bestUse: 'Baking',
    description: 'A sweet and mellow apple that works well in pies and sauces.',
    flavorProfile: 'Sweet',
    harvestSeason: 'Fall',
    popularUses: ['Baking', 'Sauces'],
  },
  {
    name: 'McIntosh',
    origin: 'Canada',
    bestUse: 'Sauce',
    description: 'A juicy and aromatic apple, ideal for making applesauce.',
    flavorProfile: 'Tart',
    harvestSeason: 'Early Fall',
    popularUses: ['Sauces', 'Juicing'],
  },
  {
    name: 'Crispin',
    origin: 'Japan',
    bestUse: 'Baking',
    description: 'A firm and sweet apple that holds up well in baked goods.',
    flavorProfile: 'Sweet',
    harvestSeason: 'Fall',
    popularUses: ['Baking', 'Snacking'],
  },
  {
    name: 'Braeburn',
    origin: 'New Zealand',
    bestUse: 'Eating Fresh',
    description: 'A balanced apple with both sweet and tart flavors, great for salads.',
    flavorProfile: 'Sweet-Tart',
    harvestSeason: 'Fall',
    popularUses: ['Snacking', 'Salads'],
  },
  {
    name: 'Pink Lady',
    origin: 'Australia',
    bestUse: 'Eating Fresh',
    description: 'A crisp and tangy apple with a pinkish hue, perfect for snacking.',
    flavorProfile: 'Tangy',
    harvestSeason: 'Late Fall',
    popularUses: ['Snacking', 'Desserts'],
  },
  {
    name: 'Ambrosia',
    origin: 'Canada',
    bestUse: 'Eating Fresh',
    description: 'A sweet and crisp apple with a mild flavor, perfect for snacking.',
    flavorProfile: 'Sweet',
    harvestSeason: 'Mid-Fall',
    popularUses: ['Snacking', 'Salads'],
  },
  {
    name: 'Jonathan',
    origin: 'USA',
    bestUse: 'Baking',
    description: 'A tart apple with a rich flavor that holds up well in baked goods.',
    flavorProfile: 'Tart',
    harvestSeason: 'Mid-Fall',
    popularUses: ['Pies', 'Sauces', 'Juicing'],
  },
  {
    name: 'Empire',
    origin: 'USA',
    bestUse: 'Eating Fresh',
    description: 'A sweet-tart apple with a firm texture, great for snacking and salads.',
    flavorProfile: 'Sweet-Tart',
    harvestSeason: 'Late Fall',
    popularUses: ['Snacking', 'Salads'],
  },
  {
    name: 'Cortland',
    origin: 'USA',
    bestUse: 'Sauces',
    description: 'A tart apple with a soft texture, ideal for making applesauce.',
    flavorProfile: 'Tart',
    harvestSeason: 'Mid-Fall',
    popularUses: ['Sauces', 'Pies'],
  },
  {
    name: 'Winesap',
    origin: 'USA',
    bestUse: 'Baking',
    description: 'A spicy and tart apple that adds a bold flavor to baked goods.',
    flavorProfile: 'Tart, Spicy',
    harvestSeason: 'Late Fall',
    popularUses: ['Baking', 'Cider'],
  },
  {
    name: 'Opal',
    origin: 'Czech Republic',
    bestUse: 'Eating Fresh',
    description: 'A sweet and crisp apple with a bright yellow skin, perfect for snacking.',
    flavorProfile: 'Sweet',
    harvestSeason: 'Winter',
    popularUses: ['Snacking', 'Juicing'],
  },
  {
    name: 'Mutsu (Crispin)',
    origin: 'Japan',
    bestUse: 'Baking',
    description: 'A firm and sweet-tart apple that works well in baked goods.',
    flavorProfile: 'Sweet-Tart',
    harvestSeason: 'Fall',
    popularUses: ['Baking', 'Snacking'],
  },
  {
    name: 'Stayman',
    origin: 'USA',
    bestUse: 'Baking',
    description: 'A tart apple with a strong flavor, ideal for pies and sauces.',
    flavorProfile: 'Tart',
    harvestSeason: 'Mid-Fall',
    popularUses: ['Pies', 'Sauces'],
  },
  {
    name: 'Gravenstein',
    origin: 'Denmark/Germany',
    bestUse: 'Juicing, Baking',
    description: 'A tart apple with a complex flavor, often used for cider and sauces.',
    flavorProfile: 'Tart',
    harvestSeason: 'Summer',
    popularUses: ['Juicing', 'Sauces', 'Baking'],
  },
  {
    name: 'Braeburn',
    origin: 'New Zealand',
    bestUse: 'Eating Fresh',
    description: 'A balanced apple with both sweet and tart flavors, great for salads.',
    flavorProfile: 'Sweet-Tart',
    harvestSeason: 'Fall',
    popularUses: ['Snacking', 'Salads'],
  },
  {
    name: 'Zestar',
    origin: 'USA',
    bestUse: 'Eating Fresh',
    description: 'A crunchy apple with a mildly tart flavor and a hint of honey.',
    flavorProfile: 'Sweet-Tart',
    harvestSeason: 'Late Summer',
    popularUses: ['Snacking', 'Salads'],
  },
  {
    name: 'Northern Spy',
    origin: 'USA',
    bestUse: 'Baking',
    description: 'A tart apple that holds up well in pies and other baked goods.',
    flavorProfile: 'Tart',
    harvestSeason: 'Late Fall',
    popularUses: ['Baking', 'Pies'],
  },
  {
    name: 'Fuji',
    origin: 'Japan',
    bestUse: 'Eating Fresh',
    description: 'A sweet and crisp apple with a firm texture, perfect for snacking.',
    flavorProfile: 'Sweet',
    harvestSeason: 'Late Fall',
    popularUses: ['Snacking', 'Salads'],
  },
  {
    name: 'Empire',
    origin: 'USA',
    bestUse: 'Eating Fresh',
    description: 'A sweet-tart apple with a firm texture, great for snacking and salads.',
    flavorProfile: 'Sweet-Tart',
    harvestSeason: 'Late Fall',
    popularUses: ['Snacking', 'Salads'],
  },
  {
    name: 'Shizuka',
    origin: 'Japan',
    bestUse: 'Eating Fresh',
    description: 'A large, sweet apple with a smooth, crisp texture.',
    flavorProfile: 'Sweet',
    harvestSeason: 'Late Fall',
    popularUses: ['Snacking', 'Salads'],
  },
  {
    name: 'SweeTango',
    origin: 'USA',
    bestUse: 'Eating Fresh',
    description: 'A cross between the Honeycrisp and Zestar apples, with a tangy, sweet flavor.',
    flavorProfile: 'Sweet-Tangy',
    harvestSeason: 'Early Fall',
    popularUses: ['Snacking', 'Salads'],
  },
  {
    name: 'Red Rome Beauty',
    origin: 'USA',
    bestUse: 'Baking',
    description: 'A tart, firm apple that is perfect for pies and sauces.',
    flavorProfile: 'Tart',
    harvestSeason: 'Late Fall',
    popularUses: ['Baking', 'Pies', 'Sauces'],
  },
  {
    name: 'Jonagold',
    origin: 'USA',
    bestUse: 'Eating Fresh',
    description: 'A cross between Jonathan and Golden Delicious, offering a sweet-tart flavor.',
    flavorProfile: 'Sweet-Tart',
    harvestSeason: 'Late Fall',
    popularUses: ['Snacking', 'Salads'],
  },
  {
    name: 'Cameo',
    origin: 'USA',
    bestUse: 'Eating Fresh',
    description: 'A crisp and sweet apple with a rich, tangy flavor.',
    flavorProfile: 'Sweet-Tangy',
    harvestSeason: 'Late Fall',
    popularUses: ['Snacking', 'Salads'],
  },
  {
    name: 'Pink Pearl',
    origin: 'USA',
    bestUse: 'Eating Fresh',
    description: 'A variety with a pink interior and a sweet-tart flavor.',
    flavorProfile: 'Sweet-Tart',
    harvestSeason: 'Late Summer',
    popularUses: ['Snacking', 'Desserts'],
  },
  {
    name: 'Lodi',
    origin: 'USA',
    bestUse: 'Sauces',
    description: 'A tart, juicy apple with a soft texture, perfect for making applesauce.',
    flavorProfile: 'Tart',
    harvestSeason: 'Early Summer',
    popularUses: ['Sauces', 'Pies'],
  },
  {
    name: 'Golden Russet',
    origin: 'USA',
    bestUse: 'Cider',
    description: 'A russeted apple known for its rich flavor, used mainly in cider production.',
    flavorProfile: 'Sweet-Tart',
    harvestSeason: 'Fall',
    popularUses: ['Cider', 'Snacking'],
  },
  {
    name: 'Arkansas Black',
    origin: 'USA',
    bestUse: 'Baking',
    description: 'A dark, crisp apple that becomes sweeter as it ripens.',
    flavorProfile: 'Sweet-Tart',
    harvestSeason: 'Late Fall',
    popularUses: ['Baking', 'Snacking'],
  },
  {
    name: 'Tydeman’s Early',
    origin: 'UK',
    bestUse: 'Eating Fresh',
    description: 'A sweet-tart apple with a juicy texture, great for snacking.',
    flavorProfile: 'Sweet-Tart',
    harvestSeason: 'Late Summer',
    popularUses: ['Snacking', 'Salads'],
  },
  {
    name: 'Waltz',
    origin: 'USA',
    bestUse: 'Eating Fresh',
    description: 'A crisp, sweet-tart apple with a firm texture, often used for snacking.',
    flavorProfile: 'Sweet-Tart',
    harvestSeason: 'Fall',
    popularUses: ['Snacking', 'Salads'],
  },
  {
    name: 'Chantecler',
    origin: 'France',
    bestUse: 'Baking',
    description: 'A sweet apple with a dense texture, perfect for baking pies.',
    flavorProfile: 'Sweet',
    harvestSeason: 'Fall',
    popularUses: ['Baking', 'Pies'],
  },
  {
    name: 'Manner',
    origin: 'Germany',
    bestUse: 'Eating Fresh',
    description: 'A sweet, aromatic apple, perfect for snacking and salads.',
    flavorProfile: 'Sweet',
    harvestSeason: 'Fall',
    popularUses: ['Snacking', 'Salads'],
  },
  {
    name: 'Suncrisp',
    origin: 'USA',
    bestUse: 'Eating Fresh',
    description: 'A crisp apple with a rich flavor, sweet with a hint of tartness.',
    flavorProfile: 'Sweet-Tart',
    harvestSeason: 'Late Fall',
    popularUses: ['Snacking', 'Juicing'],
  },
  {
    name: 'Cox’s Orange Pippin',
    origin: 'UK',
    bestUse: 'Eating Fresh',
    description: 'A highly flavorful apple with a perfect balance of sweetness and acidity.',
    flavorProfile: 'Sweet-Tart',
    harvestSeason: 'Fall',
    popularUses: ['Snacking', 'Juicing'],
  },
  {
    name: 'Sweet Sixteen',
    origin: 'USA',
    bestUse: 'Eating Fresh',
    description: 'A fragrant apple with a unique flavor that combines sweet and nutty notes.',
    flavorProfile: 'Sweet-Nutty',
    harvestSeason: 'Fall',
    popularUses: ['Snacking', 'Salads'],
  },
  {
    name: 'Duchess of Oldenburg',
    origin: 'Russia',
    bestUse: 'Sauces',
    description: 'A tart, juicy apple used primarily for making applesauce and pies.',
    flavorProfile: 'Tart',
    harvestSeason: 'Early Fall',
    popularUses: ['Sauces', 'Pies'],
  },
  {
    name: 'Tartarian',
    origin: 'USA',
    bestUse: 'Eating Fresh',
    description: 'A sweet and tart apple with a firm texture, good for snacking.',
    flavorProfile: 'Sweet-Tart',
    harvestSeason: 'Late Fall',
    popularUses: ['Snacking', 'Salads'],
  },
  {
    name: 'King of the Pippins',
    origin: 'USA',
    bestUse: 'Eating Fresh',
    description: 'A sweet, aromatic apple with an intense flavor and firm texture.',
    flavorProfile: 'Sweet',
    harvestSeason: 'Fall',
    popularUses: ['Snacking', 'Baking'],
  },
  {
    name: 'Scarlet O’Hara',
    origin: 'USA',
    bestUse: 'Baking',
    description: 'A tart, firm apple, excellent for making pies and other baked goods.',
    flavorProfile: 'Tart',
    harvestSeason: 'Fall',
    popularUses: ['Baking', 'Pies'],
  },
  {
    name: 'Vandevere',
    origin: 'USA',
    bestUse: 'Eating Fresh',
    description: 'A very sweet apple with a firm texture, ideal for snacking.',
    flavorProfile: 'Sweet',
    harvestSeason: 'Late Fall',
    popularUses: ['Snacking', 'Salads'],
  },
  {
    name: 'Windsor',
    origin: 'England',
    bestUse: 'Eating Fresh',
    description: 'A sweet and firm apple with a complex flavor, excellent for fresh eating.',
    flavorProfile: 'Sweet-Tart',
    harvestSeason: 'Late Fall',
    popularUses: ['Snacking', 'Salads'],
  },
  {
    name: 'Orleans Reinette',
    origin: 'France',
    bestUse: 'Eating Fresh',
    description: 'A sweet-tart apple with a firm texture, known for its complex flavor.',
    flavorProfile: 'Sweet-Tart',
    harvestSeason: 'Fall',
    popularUses: ['Snacking', 'Baking'],
  },
  {
    name: 'Red Astrachan',
    origin: 'Russia',
    bestUse: 'Eating Fresh',
    description: 'A tart, red-skinned apple with a juicy texture, great for snacking.',
    flavorProfile: 'Tart',
    harvestSeason: 'Early Summer',
    popularUses: ['Snacking', 'Juicing'],
  },
  {
    name: 'Opalescent',
    origin: 'USA',
    bestUse: 'Eating Fresh',
    description: 'A sweet apple with an aromatic flavor and a crisp texture.',
    flavorProfile: 'Sweet',
    harvestSeason: 'Fall',
    popularUses: ['Snacking', 'Salads'],
  },
  {
    name: 'Gravenstein',
    origin: 'Denmark',
    bestUse: 'Eating Fresh',
    description: 'A juicy apple with a sweet-tart flavor, ideal for applesauce and fresh eating.',
    flavorProfile: 'Sweet-Tart',
    harvestSeason: 'Summer',
    popularUses: ['Snacking', 'Sauces'],
  },
  {
    name: 'Cripps Pink',
    origin: 'Australia',
    bestUse: 'Eating Fresh',
    description: 'A crisp apple with a balanced sweet-tart flavor, popular for snacking.',
    flavorProfile: 'Sweet-Tart',
    harvestSeason: 'Late Fall',
    popularUses: ['Snacking', 'Salads'],
  },
  {
    name: 'Ashmead’s Kernel',
    origin: 'UK',
    bestUse: 'Eating Fresh',
    description: 'An aromatic apple with a rich, tart flavor, perfect for cider making.',
    flavorProfile: 'Tart',
    harvestSeason: 'Late Fall',
    popularUses: ['Cider', 'Snacking'],
  },
  {
    name: 'Jonathan',
    origin: 'USA',
    bestUse: 'Eating Fresh',
    description: 'A crisp, tart apple, great for eating fresh or making sauces and pies.',
    flavorProfile: 'Tart',
    harvestSeason: 'Late Fall',
    popularUses: ['Snacking', 'Sauces', 'Pies'],
  },
  {
    name: 'Wickson',
    origin: 'USA',
    bestUse: 'Cider',
    description: 'A small, intensely flavored apple often used for making cider.',
    flavorProfile: 'Sweet-Tart',
    harvestSeason: 'Fall',
    popularUses: ['Cider', 'Snacking'],
  },
  {
    name: 'Neva',
    origin: 'USA',
    bestUse: 'Eating Fresh',
    description: 'A sweet, crisp apple with a fine texture, excellent for snacking.',
    flavorProfile: 'Sweet',
    harvestSeason: 'Fall',
    popularUses: ['Snacking', 'Salads'],
  },
  {
    name: 'Waltz',
    origin: 'USA',
    bestUse: 'Eating Fresh',
    description: 'A sweet-tart apple that’s crisp and great for eating fresh or using in salads.',
    flavorProfile: 'Sweet-Tart',
    harvestSeason: 'Late Fall',
    popularUses: ['Snacking', 'Salads'],
  },
  {
    name: 'Roxbury Russet',
    origin: 'USA',
    bestUse: 'Eating Fresh',
    description: 'A sweet apple with a rough skin, known for its rich flavor.',
    flavorProfile: 'Sweet-Tart',
    harvestSeason: 'Late Fall',
    popularUses: ['Snacking', 'Baking'],
  },
  {
    name: 'King Edward',
    origin: 'UK',
    bestUse: 'Baking',
    description: 'A sweet apple, perfect for making pies and other baked goods.',
    flavorProfile: 'Sweet',
    harvestSeason: 'Late Fall',
    popularUses: ['Baking', 'Pies'],
  },
  {
    name: 'Enterprise',
    origin: 'USA',
    bestUse: 'Eating Fresh',
    description: 'A crisp and juicy apple with a sweet-tart flavor, ideal for snacking and salads.',
    flavorProfile: 'Sweet-Tart',
    harvestSeason: 'Fall',
    popularUses: ['Snacking', 'Salads'],
  },
  {
    name: 'Mutsu',
    origin: 'Japan',
    bestUse: 'Baking',
    description: 'A large apple with a sweet-tart flavor, often used for pies and baking.',
    flavorProfile: 'Sweet-Tart',
    harvestSeason: 'Fall',
    popularUses: ['Baking', 'Pies'],
  },
  {
    name: 'Spartan',
    origin: 'Canada',
    bestUse: 'Eating Fresh',
    description: 'A crisp, sweet apple with a rich flavor, great for fresh eating.',
    flavorProfile: 'Sweet',
    harvestSeason: 'Fall',
    popularUses: ['Snacking', 'Salads'],
  },
  {
    name: 'Baldwin',
    origin: 'USA',
    bestUse: 'Baking',
    description: 'A sweet and tart apple, excellent for making applesauce and pies.',
    flavorProfile: 'Sweet-Tart',
    harvestSeason: 'Late Fall',
    popularUses: ['Baking', 'Sauces'],
  },
  {
    name: 'Almaty',
    origin: 'Kazakhstan',
    bestUse: 'Eating Fresh',
    description: 'A fragrant and juicy apple, great for eating fresh or making jams.',
    flavorProfile: 'Sweet',
    harvestSeason: 'Fall',
    popularUses: ['Snacking', 'Jams'],
  },
  {
    name: 'Bramley',
    origin: 'UK',
    bestUse: 'Cooking',
    description: 'A large, tart apple perfect for making pies and sauces.',
    flavorProfile: 'Tart',
    harvestSeason: 'Late Fall',
    popularUses: ['Baking', 'Sauces'],
  },
  {
    name: 'Opal',
    origin: 'Czech Republic',
    bestUse: 'Eating Fresh',
    description: 'A sweet, crunchy apple with a bright yellow color, perfect for snacking.',
    flavorProfile: 'Sweet',
    harvestSeason: 'Fall',
    popularUses: ['Snacking', 'Salads'],
  },
  {
    name: 'Tydeman’s Late Orange',
    origin: 'UK',
    bestUse: 'Eating Fresh',
    description: 'A sweet and tart apple with an orange tint, great for fresh eating.',
    flavorProfile: 'Sweet-Tart',
    harvestSeason: 'Late Fall',
    popularUses: ['Snacking', 'Salads'],
  },
  {
    name: 'Cox’s Orange Pippin',
    origin: 'UK',
    bestUse: 'Eating Fresh',
    description: 'A classic British apple, known for its sweet-tart, aromatic flavor.',
    flavorProfile: 'Sweet-Tart',
    harvestSeason: 'Late Fall',
    popularUses: ['Snacking', 'Baking'],
  },
  {
    name: 'Empire',
    origin: 'USA',
    bestUse: 'Eating Fresh',
    description: 'A cross between Red Delicious and McIntosh, known for its sweet-tart flavor.',
    flavorProfile: 'Sweet-Tart',
    harvestSeason: 'Fall',
    popularUses: ['Snacking', 'Salads'],
  },
  {
    name: 'Snow Sweet',
    origin: 'USA',
    bestUse: 'Eating Fresh',
    description: 'A sweet, crisp apple with a snow-white flesh, great for snacking.',
    flavorProfile: 'Sweet',
    harvestSeason: 'Late Fall',
    popularUses: ['Snacking', 'Salads'],
  },
  {
    name: 'Jonagold',
    origin: 'USA',
    bestUse: 'Eating Fresh',
    description: 'A large, sweet-tart apple, often used in baking and fresh eating.',
    flavorProfile: 'Sweet-Tart',
    harvestSeason: 'Late Fall',
    popularUses: ['Snacking', 'Baking'],
  },
  {
    name: 'Stayman',
    origin: 'USA',
    bestUse: 'Cider',
    description: 'A tart apple with a complex flavor, often used in cider making.',
    flavorProfile: 'Tart',
    harvestSeason: 'Late Fall',
    popularUses: ['Cider', 'Baking'],
  },
  {
    name: 'Sweet 16',
    origin: 'USA',
    bestUse: 'Eating Fresh',
    description: 'A sweet, juicy apple with a unique, almost honey-like flavor.',
    flavorProfile: 'Sweet',
    harvestSeason: 'Fall',
    popularUses: ['Snacking', 'Salads'],
  },
  {
    name: 'Northern Spy',
    origin: 'USA',
    bestUse: 'Baking',
    description: 'A tart, firm apple ideal for pies and crisps.',
    flavorProfile: 'Tart',
    harvestSeason: 'Fall',
    popularUses: ['Baking', 'Pies'],
  },
  {
    name: 'Red Romaine',
    origin: 'USA',
    bestUse: 'Eating Fresh',
    description: 'A mild and sweet apple with a red skin and firm texture, great for snacking.',
    flavorProfile: 'Sweet',
    harvestSeason: 'Fall',
    popularUses: ['Snacking', 'Salads'],
  },
  {
    name: 'Wagner',
    origin: 'USA',
    bestUse: 'Eating Fresh',
    description: 'A small, aromatic apple with a rich, sweet-tart flavor.',
    flavorProfile: 'Sweet-Tart',
    harvestSeason: 'Late Fall',
    popularUses: ['Snacking', 'Baking'],
  },
  {
    name: 'Royal Gala',
    origin: 'New Zealand',
    bestUse: 'Eating Fresh',
    description: 'A sweet, crisp apple, perfect for snacking or adding to fruit salads.',
    flavorProfile: 'Sweet',
    harvestSeason: 'Late Summer',
    popularUses: ['Snacking', 'Salads'],
  },
  {
    name: 'Winesap',
    origin: 'USA',
    bestUse: 'Cider',
    description: 'A tart, spicy apple used commonly in cider making.',
    flavorProfile: 'Tart-Spicy',
    harvestSeason: 'Late Fall',
    popularUses: ['Cider', 'Baking'],
  },
  {
    name: 'Ashmead’s Kernel',
    origin: 'UK',
    bestUse: 'Eating Fresh',
    description: 'A small, russeted apple with a complex, sweet-tart flavor.',
    flavorProfile: 'Sweet-Tart',
    harvestSeason: 'Fall',
    popularUses: ['Snacking', 'Cider'],
  },
  {
    name: 'Mutsu (Crispin)',
    origin: 'Japan',
    bestUse: 'Eating Fresh',
    description: 'A large, firm apple with a sweet-tart flavor, similar to Golden Delicious.',
    flavorProfile: 'Sweet-Tart',
    harvestSeason: 'Fall',
    popularUses: ['Snacking', 'Baking'],
  },
  {
    name: 'Golden Russet',
    origin: 'USA',
    bestUse: 'Cider',
    description: 'A russet apple with a distinctive flavor, used primarily in cider making.',
    flavorProfile: 'Tart',
    harvestSeason: 'Fall',
    popularUses: ['Cider', 'Baking'],
  },
  {
    name: 'Roxbury Russet',
    origin: 'USA',
    bestUse: 'Cider',
    description: 'A small, russeted apple with a complex flavor, often used for cider.',
    flavorProfile: 'Tart',
    harvestSeason: 'Fall',
    popularUses: ['Cider', 'Snacking'],
  },
  {
    name: 'Lodi',
    origin: 'USA',
    bestUse: 'Baking',
    description: 'A tart apple with a strong flavor, great for pies and baking.',
    flavorProfile: 'Tart',
    harvestSeason: 'Summer',
    popularUses: ['Baking', 'Canning'],
  },
  {
    name: 'Rome Beauty',
    origin: 'USA',
    bestUse: 'Baking',
    description: 'A tart apple that holds its shape well when baked, often used for pies.',
    flavorProfile: 'Tart',
    harvestSeason: 'Fall',
    popularUses: ['Baking', 'Pies'],
  },
  {
    name: 'Fuji Supreme',
    origin: 'Japan',
    bestUse: 'Eating Fresh',
    description: 'A variation of the Fuji apple with a more intense sweetness and crisp texture.',
    flavorProfile: 'Sweet',
    harvestSeason: 'Late Fall',
    popularUses: ['Snacking', 'Salads'],
  },
  {
    name: 'Gravenstein',
    origin: 'Denmark',
    bestUse: 'Cider',
    description: 'A crisp and tart apple often used in cider production and pies.',
    flavorProfile: 'Tart',
    harvestSeason: 'Summer',
    popularUses: ['Cider', 'Baking'],
  },
  {
    name: 'Pippin',
    origin: 'USA',
    bestUse: 'Baking',
    description: 'A tart apple with a firm texture, great for pies and sauces.',
    flavorProfile: 'Tart',
    harvestSeason: 'Fall',
    popularUses: ['Baking', 'Sauces'],
  },
  {
    name: 'Waltz',
    origin: 'USA',
    bestUse: 'Eating Fresh',
    description: 'A sweet and tangy apple, perfect for fresh eating and snacking.',
    flavorProfile: 'Sweet-Tangy',
    harvestSeason: 'Fall',
    popularUses: ['Snacking', 'Salads'],
  },
  {
    name: 'Zestar!',
    origin: 'USA',
    bestUse: 'Eating Fresh',
    description: 'A sweet-tart, early-season apple with a crisp texture.',
    flavorProfile: 'Sweet-Tart',
    harvestSeason: 'Late Summer',
    popularUses: ['Snacking', 'Salads'],
  },
  {
    name: 'Suncrisp',
    origin: 'USA',
    bestUse: 'Eating Fresh',
    description: 'A sweet-tart apple with a crisp texture, excellent for fresh eating.',
    flavorProfile: 'Sweet-Tart',
    harvestSeason: 'Fall',
    popularUses: ['Snacking', 'Salads'],
  },
  {
    name: 'Pink Pearl',
    origin: 'USA',
    bestUse: 'Eating Fresh',
    description: 'A pink-fleshed apple with a tart flavor, ideal for snacking.',
    flavorProfile: 'Tart',
    harvestSeason: 'Fall',
    popularUses: ['Snacking', 'Salads'],
  },
  {
    name: 'Kidd’s Orange Red',
    origin: 'New Zealand',
    bestUse: 'Eating Fresh',
    description: 'A red-skinned apple with a sweet and tangy flavor, perfect for snacking.',
    flavorProfile: 'Sweet-Tangy',
    harvestSeason: 'Late Summer',
    popularUses: ['Snacking', 'Salads'],
  },
  {
    name: 'Early Harvest',
    origin: 'USA',
    bestUse: 'Eating Fresh',
    description: 'A sweet, early-season apple perfect for fresh eating.',
    flavorProfile: 'Sweet',
    harvestSeason: 'Summer',
    popularUses: ['Snacking', 'Salads'],
  },
  {
    name: 'Jonagold',
    origin: 'USA',
    bestUse: 'Eating Fresh',
    description: 'A sweet-tart apple with honeyed flavor, great for snacking and baking.',
    flavorProfile: 'Sweet-Tart',
    harvestSeason: 'Fall',
    popularUses: ['Snacking', 'Baking'],
  },
  {
    name: 'Opal',
    origin: 'Czech Republic',
    bestUse: 'Eating Fresh',
    description: 'A sweet, crisp apple with a golden yellow color and a firm texture.',
    flavorProfile: 'Sweet',
    harvestSeason: 'Late Fall',
    popularUses: ['Snacking', 'Salads'],
  },
  {
    name: 'Braeburn',
    origin: 'New Zealand',
    bestUse: 'Eating Fresh',
    description: 'A sweet-tart apple with a firm texture, great for snacking or cooking.',
    flavorProfile: 'Sweet-Tart',
    harvestSeason: 'Fall',
    popularUses: ['Snacking', 'Salads'],
  },
  {
    name: 'Cripps Pink',
    origin: 'Australia',
    bestUse: 'Eating Fresh',
    description: 'A crisp and tangy apple, often referred to as Pink Lady, with a distinct rosy color.',
    flavorProfile: 'Tangy',
    harvestSeason: 'Late Fall',
    popularUses: ['Snacking', 'Desserts'],
  },
  {
    name: 'Empire',
    origin: 'USA',
    bestUse: 'Eating Fresh',
    description: 'A sweet-tart apple, great for fresh eating, juicing, and salads.',
    flavorProfile: 'Sweet-Tart',
    harvestSeason: 'Fall',
    popularUses: ['Snacking', 'Salads'],
  },
  {
    name: 'Cortland',
    origin: 'USA',
    bestUse: 'Baking',
    description: 'A mildly tart apple with tender, juicy flesh, ideal for pies and salads.',
    flavorProfile: 'Tart',
    harvestSeason: 'Fall',
    popularUses: ['Baking', 'Salads'],
  },
  {
    name: 'Stayman',
    origin: 'USA',
    bestUse: 'Cider',
    description: 'A tart apple with complex flavors, often used in cider making.',
    flavorProfile: 'Tart',
    harvestSeason: 'Fall',
    popularUses: ['Cider', 'Baking'],
  },
  {
    name: 'Northern Spy',
    origin: 'USA',
    bestUse: 'Baking',
    description: 'A tart apple that retains its texture when baked, perfect for pies and crisps.',
    flavorProfile: 'Tart',
    harvestSeason: 'Fall',
    popularUses: ['Baking', 'Pies'],
  },
  {
    name: 'Waltz',
    origin: 'USA',
    bestUse: 'Eating Fresh',
    description: 'A sweet-tangy apple with a crisp texture, perfect for fresh eating.',
    flavorProfile: 'Sweet-Tangy',
    harvestSeason: 'Fall',
    popularUses: ['Snacking', 'Salads'],
  },
  {
    name: 'Albemarle Pippin',
    origin: 'USA',
    bestUse: 'Eating Fresh',
    description: 'A tart apple with a rich, complex flavor, great for fresh eating and pies.',
    flavorProfile: 'Tart',
    harvestSeason: 'Fall',
    popularUses: ['Snacking', 'Pies'],
  },
  {
    name: 'Tydeman’s Late',
    origin: 'UK',
    bestUse: 'Eating Fresh',
    description: 'A late-season apple with a sweet-tart flavor, ideal for fresh eating and storage.',
    flavorProfile: 'Sweet-Tart',
    harvestSeason: 'Late Fall',
    popularUses: ['Snacking', 'Storage'],
  },
  {
    name: 'Cameo',
    origin: 'USA',
    bestUse: 'Eating Fresh',
    description: 'A crisp apple with a sweet-tart flavor, great for snacking and salads.',
    flavorProfile: 'Sweet-Tart',
    harvestSeason: 'Fall',
    popularUses: ['Snacking', 'Salads'],
  },
  {
    name: 'Jersey Mac',
    origin: 'USA',
    bestUse: 'Eating Fresh',
    description: 'A sweet-tart apple that’s excellent for fresh eating, often picked early in the season.',
    flavorProfile: 'Sweet-Tart',
    harvestSeason: 'Early Fall',
    popularUses: ['Snacking', 'Juicing'],
  },
  {
    name: 'Ginger Gold',
    origin: 'USA',
    bestUse: 'Eating Fresh',
    description: 'A sweet, early-season apple with a tangy flavor, perfect for snacking.',
    flavorProfile: 'Sweet-Tangy',
    harvestSeason: 'Early Fall',
    popularUses: ['Snacking', 'Salads'],
  },
  {
    name: 'Pawpaw',
    origin: 'USA',
    bestUse: 'Eating Fresh',
    description: 'A unique fruit with a custard-like texture, often confused with apples but technically a different fruit.',
    flavorProfile: 'Sweet-Tangy',
    harvestSeason: 'Late Summer',
    popularUses: ['Snacking'],
  },
  {
    name: 'Mutsu',
    origin: 'Japan',
    bestUse: 'Baking',
    description: 'A large, sweet-tart apple with a juicy, firm texture, perfect for pies and crisps.',
    flavorProfile: 'Sweet-Tart',
    harvestSeason: 'Late Fall',
    popularUses: ['Baking', 'Pies'],
  },
  {
    name: 'Winesap',
    origin: 'USA',
    bestUse: 'Eating Fresh',
    description: 'A firm, tart apple with a spicy-sweet flavor, great for snacking and cider making.',
    flavorProfile: 'Spicy-Sweet',
    harvestSeason: 'Fall',
    popularUses: ['Snacking', 'Cider'],
  },
  {
    name: 'Tartarian',
    origin: 'USA',
    bestUse: 'Eating Fresh',
    description: 'A tart apple with a crisp texture, ideal for fresh eating or making applesauce.',
    flavorProfile: 'Tart',
    harvestSeason: 'Fall',
    popularUses: ['Snacking', 'Sauces'],
  },
  {
    name: 'Gravenstein',
    origin: 'Denmark',
    bestUse: 'Eating Fresh',
    description: 'A sweet-tart apple with a soft, juicy flesh, ideal for snacking and making applesauce.',
    flavorProfile: 'Sweet-Tart',
    harvestSeason: 'Late Summer',
    popularUses: ['Snacking', 'Sauces'],
  },
  {
    name: 'Zestar!',
    origin: 'USA',
    bestUse: 'Eating Fresh',
    description: 'A sweet-tart apple with a crisp texture, perfect for fresh eating and early-season harvesting.',
    flavorProfile: 'Sweet-Tart',
    harvestSeason: 'Early Fall',
    popularUses: ['Snacking', 'Salads'],
  },
  {
    name: 'Pink Pearl',
    origin: 'USA',
    bestUse: 'Eating Fresh',
    description: 'A unique apple with a pinkish flesh and a sweet-tart flavor, great for snacking and baking.',
    flavorProfile: 'Sweet-Tart',
    harvestSeason: 'Late Summer',
    popularUses: ['Snacking', 'Baking'],
  },
  {
    name: 'Red Rome Beauty',
    origin: 'USA',
    bestUse: 'Baking',
    description: 'A tart, firm apple with a deep red color, perfect for baking and pies.',
    flavorProfile: 'Tart',
    harvestSeason: 'Fall',
    popularUses: ['Baking', 'Pies'],
  },
  {
    name: 'Baldwin',
    origin: 'USA',
    bestUse: 'Eating Fresh',
    description: 'A tart apple with a firm, crisp texture, perfect for snacking and storing.',
    flavorProfile: 'Tart',
    harvestSeason: 'Fall',
    popularUses: ['Snacking', 'Storage'],
  },
  {
    name: 'Opalescent',
    origin: 'USA',
    bestUse: 'Eating Fresh',
    description: 'A bright yellow apple with a sweet flavor and crisp texture, ideal for fresh eating.',
    flavorProfile: 'Sweet',
    harvestSeason: 'Late Summer',
    popularUses: ['Snacking', 'Salads'],
  },
  {
    name: 'Hubbardston Nonesuch',
    origin: 'USA',
    bestUse: 'Baking',
    description: 'A firm, tart apple that holds its shape when baked, perfect for pies and crisps.',
    flavorProfile: 'Tart',
    harvestSeason: 'Fall',
    popularUses: ['Baking', 'Pies'],
  },
  {
    name: 'Ashmead’s Kernel',
    origin: 'UK',
    bestUse: 'Eating Fresh',
    description: 'A small, firm apple with a sweet-tart flavor, often used for cider-making.',
    flavorProfile: 'Sweet-Tart',
    harvestSeason: 'Fall',
    popularUses: ['Cider', 'Snacking'],
  },
  {
    name: 'Egremont Russet',
    origin: 'UK',
    bestUse: 'Eating Fresh',
    description: 'A russeted apple with a sweet, nutty flavor, perfect for fresh eating and cider making.',
    flavorProfile: 'Nutty',
    harvestSeason: 'Fall',
    popularUses: ['Cider', 'Snacking'],
  },
  {
    name: 'Kingston Black',
    origin: 'UK',
    bestUse: 'Cider',
    description: 'A highly regarded cider apple known for its deep flavor and tannic properties.',
    flavorProfile: 'Tannic',
    harvestSeason: 'Fall',
    popularUses: ['Cider'],
  },
];

export const seedAppleVarieties = async () => {
  console.log('Seeding Apple Varieties...');
  try {
    await prisma.appleVariety.createMany({ data: appleVarieties });
    console.log('Apple Varieties seeded successfully!');
  } catch (error) {
    console.error('Error seeding Apple Varieties:', error);
  } finally {
    await prisma.$disconnect();
  }
};