import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

const appleVarieties = [
  {
    variety: "Honeycrisp",
    calories: 80,
    carbohydrates: 22,
    fiber: 5,
    sugars: 16,
    protein: 0.5,
    fat: 0,
    vitamin_c: 8,
    potassium: 200,
    calcium: 10,
    magnesium: 8,
    iron: 0.2,
    vitamin_a: 100,
    vitamin_k: 2,
    vitamin_e: 0.3,
  },
  {
    variety: "Granny Smith",
    calories: 70,
    carbohydrates: 19,
    fiber: 4,
    sugars: 14,
    protein: 0.5,
    fat: 0,
    vitamin_c: 9,
    potassium: 210,
    calcium: 12,
    magnesium: 7,
    iron: 0.3,
    vitamin_a: 90,
    vitamin_k: 2.5,
    vitamin_e: 0.4,
  },
  {
    variety: "Fuji",
    calories: 90,
    carbohydrates: 25,
    fiber: 4,
    sugars: 20,
    protein: 0.5,
    fat: 0,
    vitamin_c: 8.5,
    potassium: 195,
    calcium: 11,
    magnesium: 9,
    iron: 0.2,
    vitamin_a: 98,
    vitamin_k: 2.2,
    vitamin_e: 0.33,
  },
  {
    variety: "Gala",
    calories: 80,
    carbohydrates: 22,
    fiber: 5,
    sugars: 17,
    protein: 0.5,
    fat: 0,
    vitamin_c: 7.5,
    potassium: 180,
    calcium: 10,
    magnesium: 7,
    iron: 0.2,
    vitamin_a: 95,
    vitamin_k: 2,
    vitamin_e: 0.3,
  },
  {
    variety: "Red Delicious",
    calories: 80,
    carbohydrates: 22,
    fiber: 5,
    sugars: 16,
    protein: 0.5,
    fat: 0,
    vitamin_c: 8,
    potassium: 200,
    calcium: 9,
    magnesium: 7,
    iron: 0.2,
    vitamin_a: 92,
    vitamin_k: 2,
    vitamin_e: 0.3,
  },
  {
    variety: "Pink Lady",
    calories: 85,
    carbohydrates: 23,
    fiber: 5,
    sugars: 17,
    protein: 0.5,
    fat: 0,
    vitamin_c: 8.2,
    potassium: 205,
    calcium: 11,
    magnesium: 8,
    iron: 0.3,
    vitamin_a: 100,
    vitamin_k: 2.1,
    vitamin_e: 0.35,
  },
  {
    variety: "Golden Delicious",
    calories: 80,
    carbohydrates: 22,
    fiber: 4,
    sugars: 17,
    protein: 0.5,
    fat: 0,
    vitamin_c: 7.8,
    potassium: 190,
    calcium: 10,
    magnesium: 8,
    iron: 0.2,
    vitamin_a: 96,
    vitamin_k: 2,
    vitamin_e: 0.3,
  },
  {
    variety: "Braeburn",
    calories: 82,
    carbohydrates: 22,
    fiber: 5,
    sugars: 16,
    protein: 0.5,
    fat: 0,
    vitamin_c: 7.9,
    potassium: 195,
    calcium: 10,
    magnesium: 8,
    iron: 0.2,
    vitamin_a: 97,
    vitamin_k: 2,
    vitamin_e: 0.3,
  }
];

export const seedAppleVarietiesNutrition = async () => {
  console.log("Seeding Apple Varieties Nutrition...");
  try {
    await prisma.nutrition.createMany({
      data: appleVarieties.map(apple => ({ fruit: "Apple", ...apple }))
    });
    console.log("Apple Varieties nutrition seeded successfully!");
  } catch (error) {
    console.error("Error seeding Apple Varieties Nutrition:", error);
  } finally {
    await prisma.$disconnect();
  }
};
